---
title: 'Imprint and accessibility statement'
author: "David Kneis (firstname.lastname @ tu-dresden.de)"
date: "`r Sys.Date()`"
format:
  html:
    number-sections: true
    toc: true
    toc-depth: 3
    toc-location: left
    embed-resources: true    
---

```{r echo=FALSE}
options(width=120) # keep this to trigger proper date in header
```

# Purpose

The contents provided on https://amr-env.github.io is meant to support
research on antimicrobial resistance with a focus on environmental
settings. The contents reflects work in progress and the information
provided may not be sufficiently validated. Consequently, the
information is not intended to be used for any serious purpose or
application. In case of doubt, please contact the maintainer of the page
https://amr-env.github.io (see contact details below) or the involved
researchers (contact details may be provided as per sub-directory).

# Responsibilities / Contact

The page https://amr-env.github.io and its sub-directories are
managed and maintained by David Kneis. If you have any questions
regarding contents or technical issues, please contact:

| Dr. David Kneis
| Institute of Hydrobiology
| Technische Universität Dresden
| 01062 Dresden
| Germany
| 
| Email: firstname.lastname@tu-dresden.de
|        (replace firstname by 'David' and lastname by 'Kneis')
| Phone: +49 351 463 - 32 32 9

# Data protection declaration

The service provided on https://amr-env.github.io and
its sub-directories is not intended to process personal data. In
particular, within the responsibilities of the maintainer (David Kneis,
contact details above), no tracking cookies are used to record or
analyze user movement and behavior on the websites. 

In accordance with German law (Art. 6 para. 1 letter f GDPR) you have
the right to obtain information on the data processed concerning you
and/or to request the correction of inaccurate data. You also have the
right to erasure and restriction of processing as well as the right to
object to the processing. In this regard, you can contact the maintainer
(David Kneis, contact details above) at any time.

# Accessibility statement

This accessibility statement applies to https://amr-env.github.io and
its sub-directories. This website is managed and maintained by 
David Kneis (contact details above). The maintainer is committed to
making all contents accessible, in accordance with the respective
German laws (BfWebG, BITV 2.0) implementing EU Directive 2016/2102.

This statement was prepared and last reviewed on 2023-12-23 by David
Kneis based on a self-assessment.

The contents of https://amr-env.github.io and
its sub-directories is partially compliant with the indicated legal
requirements. In particular, outcomes of ongoing research in the form
of graphics and scientific documents are considered preliminary. Such
preliminary items are not optimized for accessibility because of
disproportionate effort. If you are interested in any content being
currently inaccessible, please contact the maintainer, David Kneis 
(contact details above) to find a solution that suits your particular
needs.
